import p1 from '../Assets/model.png'
import p2 from '../Assets/women-banner.png'

let all_product = [
    {
        id:1,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'kid',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:2,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'kid',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:3,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'kid',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:4,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'women',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },{
        id:5,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'women',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:6,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'women',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:7,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'women',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:8,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'men',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:9,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'men',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:10,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'men',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    }, {
        id:11,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'men',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    }, {
        id:12,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'women',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:13,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'kid',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    },
    {
        id:14,
        name:'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
        category:'men',
        image:p1,
        imageback: p2,
        new_price: 85.00,
        old_price: 120.50,
    }
    
];

export default all_product ;